baseURL = 'https://aipe-jo.github.io/'
languageCode = 'fr-FR'
title = "L'asso indépendante des parents d'élèves de l'école Justin Oudin"
theme = "aipe-jo"

resourceDir = "../resources"

Paginate = 6           # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
favicon = ""
site_logo = "/images/logo.jpg"
description = "The last theme you'll ever need. Maybe."
mail = "aipejo92@gmail.com"
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
recent_posts_number = 2

## social site
[[params.social]]
title = "Facebook"
icon = "/images/icons/facebook.svg"
link = "https://www.facebook.com/aipejo"

[[params.social]]
title = "Instagram"
icon = "/images/icons/instagram.svg"
link = "https://www.instagram.com/asso_parents_justinoudin"

[[params.social]]
title = "Youtube"
icon = "/images/icons/youtube.svg"
link = "https://www.youtube.com/channel/UCxL3XFo68xrVlSfNfXqWoRA"

[privacy]
  [privacy.disqus]
    disable = true

  [privacy.googleAnalytics]
    disable = true

  [privacy.instagram]
    disable = true

  [privacy.twitter]
    disable = true

  [privacy.vimeo]
    disable = true

  [privacy.youtube]
    disable = false
    privacyEnhanced = true
